language: node_js
node_js:
- '8'
cache: yarn
addons:
  sonarcloud:
    organization: "hmcts"
    token:
      secure: "Z+6Kw0Na8I0/9wrdDRAg8AXzw06PnUZrgAIU6PcrnGZEzqNpB7NHIOcE/zubXSFx7Ra4+j+4ccs2QLlYxw1EzzNpsVjv4UKonEBcQPF+4/UDv2Ur9ZeVGMMow2q5smCfxe9obE1VGKK2zfKSGpVjVbm71qxZzPW+CNhRki+dLbL64cDHgaoxRZVV+kUP+6lgG1a2ZMu58HQZJ5qjhmeqepYbZFFj8ZSRw3vBWbWgU7wx8cS5Iojssac/ymRWIvdwWyoUJ7MgDPCwOarlhozflOirCyYbN102NbPAk/mzQemywidodpHfv7/KyZVSZU7/wOWzWTXaRCWQh/SfTkm8Ye5CWZWMGJz7R3+458RnsA6tNymutlZuu/PXZy+GIcqgQ4LqG84lWFRjboyM/DoGDrqmaJ1WAjRmMnwRyTc8k4JHU2rf1BIm87ZgaRLX/4BniE/ayFFWHbbf7xJoJM6rOcKG10BBEe3cCz4n4bjDW7qeDC0TGS90GnGXHWM/0nWk8lDMGksnKLhtliawarPpDZKj8J00YLaxHl6NJ9kxaBkm3NwMnNagoCT2mrMVhEYpQmRK7WNkXh1Tsd/p/4b9ZSauRZAJl8Qni+OIXFqZ4U6ZBLqf5Aa+4XJvBXcUnVjxvUnL3k5UyFgkGluETJzzT9KNS7uuSbyNeC56EPy5gHs="
script:
- yarn --version
- yarn check --integrity
- yarn test
- sonar-scanner

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: FmOlkV/02sCnGhAla9Yf8bDjZPKrvp2DA8OClxlbt6L3U5pDfNYU+C9KNDqI/2GI49Ln5Zw/q/yEB4D2OHVZWfLc/mTWpzjNPwLlqUc2+lGeuXfHAddTLOJRLelrjJfIrXBlr9t/8EZS7D/XbfC/Qcnol5SGGPrAb2/wRssa4TEZyuPs0Vn5Ij6gQtghYOSZSh+YahuS9P7/+4qaufmzUV9/Wg5tz65j35V203o7B6wEEJxNjIZfM8Ao77hwsV93zjW2NBCwMu8SgF9l1TVejbxr5c/PdcfvFs+um0XlWbipxErHk2DAoe+63yrRFWcmKZ7Hn/06340Ywoy8GE6dlqbXD6M1l5L3EXXnpaPR5f/2fWjzzPHuSfOQlW24g4yOzBilOmndFLKb6P0IMJmzqUbz9ivV5Nnrssc0fS5y2oFunJEj7GX65HJXyBh3fnRqTjJlU4Ay3ukNas3rFR10QtQ5thh7oWbwjR8L9ogXBIVo4iXynx+pY9rAEfpMc+O5SSwr1y3qproezvHSV/A5IB0fEZXb60JYDKvm0Ug7gu25U+2vA6XaShm49qCFSgrObLTAzxHYliJ+D+d+OxGi5oar+JctHNgVZjaeW9NDGI+Ekb+6K6ntl4ylqDMiKcQ1dh4ZWHhUeggCSsJszGJTDZBnjSrXVTTXj9A/LOsLdes=
  on:
    tags: true
    repo: hmcts/div-idam-test-harness
